### ISSUE TITLE
Provide script to inject content in an ARM template

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#11]
Provide script to inject content in an ARM template

**Comment by mbraekman** [comment]
Based on the following script:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FInject-ArmContent.ps1

**Comment by mbraekman** [comment]
@stijnmoreels could you prioritize this one, over the other open issues related to milestone v0.1.0
The reason for this is that we're going to reschedule some of the issues to v0.2.0:
- otherwise v0.1.0 would become to big
- v0.1.0 can already be used on projects (this command would be of most use to some ;))

**Comment by mbraekman** [comment]
P.S.: I'll be updating the milestone on the other open issues later today

**Comment by stijnmoreels** [comment]
Yes, I was already working on that offline but I didn't got the test to work bc there's not exactly a valid error-handling system in place. So, I'll probably have to debug it to find how the script actually expect it's input.
