### ISSUE TITLE
Provide script to upsert users in APIM (developer portal)

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#170]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to easily manage or automate the creation of users in APIM to grant them access to the Developer Portal.
Because of this, this remains a manual step.

**Describe the solution you'd like**
This can be automated by using the REST API to take care of the creation/update of users, defining whether they get access to the legacy dev port, whether they need to be invited,...

A first test has been created here:
https://github.com/mbraekman/Powershell/blob/master/Azure/APIM-InviteUserToDevPortal.ps1

What isn't included in this PoC-scripts is:
- the removal of users
- adding/removing users to groups (+ group-management)

**Comment by pim-simons** [comment]
@mbraekman  is this still relevant, it seems that there are Az scripts that offer this functionality (or maybe I'm not fully understanding the feature request 😉)

See: 
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementuser?view=azps-8.0.0
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/set-azapimanagementuser?view=azps-8.0.0
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.0.0

**Comment by mbraekman** [comment]
Only thing I do not notice at first glance from the docs to those operations in the Az-module, is support for:
 - invite vs signup (user provides pwd vs pwd is set via script)
 - send a notification after registering (bool)
 - grant access to legacy developer portal vs "new" dev portal

The last two might be ignored, but the first option I would consider quite critical?

**Comment by pim-simons** [comment]
@mbraekman thanks for your input! Sorry for the late response, a lot of things got in the way 😒
Good point about the invite part 👍🏻 

I think we can create a script (based on [https://github.com/mbraekman/Powershell/blob/master/Azure/APIM-InviteUserToDevPortal.ps1](https://github.com/mbraekman/Powershell/blob/master/Azure/APIM-InviteUserToDevPortal.ps1?rgh-link-date=2021-05-01T12%3A00%3A58Z)) that will create a user and gives the option to invite or signup. 

Regarding:
>What isn't included in this PoC-scripts is:
>
>    the removal of users
>    adding/removing users to groups (+ group-management)

I don't think we have to include this, since users can be removed using https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuser?view=azps-8.0.0 and group management can be done with https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/add-azapimanagementusertogroup?view=azps-8.0.0, https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementuserfromgroup?view=azps-8.0.0, https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/add-azapimanagementproducttogroup?view=azps-8.0.0 and https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/remove-azapimanagementproductfromgroup?view=azps-8.0.0.
@mbraekman  do you agree or any other ideas?

**Comment by mbraekman** [comment]
Creating the script to remove users or assign groups definitely isn't high-prio, since the az-module offers some options.
An option would be to provide a RemoveUser-function that allows people to only specify the email address, instead of having to perform a _Get-AzApiManagementUser_ to retrieve the userId, themselves. 
All of this logic could become part of the newly created function.
Is this an absolute mush-have? _No_
Would it be useful and make lives easier for some? _Yes_

_The same applies to the group-related stuff._

As mentioned before, up to you to decide whether this should end up on the backlog. 
Personally, I would kind of like the idea of having something handling the complexities/error-handling for me, so I don't have to combine several functions myself. Especially if this is something I'd be using across multiple projects (which would result in copy/pasting).

**Comment by pim-simons** [comment]
> Creating the script to remove users or assign groups definitely isn't high-prio, since the az-module offers some options. An option would be to provide a RemoveUser-function that allows people to only specify the email address, instead of having to perform a _Get-AzApiManagementUser_ to retrieve the userId, themselves. All of this logic could become part of the newly created function. Is this an absolute must-have? _No_ Would it be useful and make lives easier for some? _Yes_

Created a new issue specifically for this [here](https://github.com/arcus-azure/arcus.scripting/issues/320)
