### ISSUE TITLE
Provide script set to build a simple Azure Cognitive Search & Form Recognizer resource set

### ISSUE THREAD

**Issue by paul-warwick-cdt** [arcus-azure/arcus.scripting#22]
Provide a script set to allow inclusion of a cognitive-component into Azure through a YAML pipeline

The solution I would like to offer would include:

(A) YML parent pipeline with validate (via template), build & release (via template) stages:

(B) YML template to Validate ARM template

(C) YML template to Release:
[1] Build new resource Group
[2] Apply ARM template (& parameter file) to build: 
- Storage Account (or as a separate infra related ARM template)
- Cognitive Service- Skillset (as yet unused)
- Cognitive Service- Form Recognizer
- Azure Search Service

[3] Apply New-PreMapBuild.ps1 to set up a Synonym Map (Index dependency)
[4] Apply New-SearchIndexes.ps1 to load an Index (or indexes) from a folder
[5] Apply New-ModelUpload.ps1 to upload 3 sample files into a blob storage Container
[6] Apply Train-Model.ps1 to use native training of the Form Recognizer against the sample models

This capability would assume usage from within an Azure DevOps Repo environment with some simple set-up.

As a result of this process; building blocks would be in place to further enhance and develop cognitive services for a customer.

The Form Recognizer to Sample Search index is not linked and implemented.

Alternatives:
[+] More granular script examples
[+] Less DevOps dependency
[+] Some considerations are relevant because of preview status of cognitive components
[+] Components implemented as linked

**Comment by tomkerkhove** [comment]
Hi Paul, can you tweak the formatting a bit because it feels like you want to put some structure in your request but it's not formatted correctly?

So basically this issue is to track a set of scripts?

**Comment by paul-warwick-cdt** [comment]
Submission format improved.  Yes this issue to offer a set of scripts.

**Comment by mbraekman** [comment]
Hi Paul, first off, thanks for contributing!

What we're looking at here is providing a PS-module (or multiple, for instance in 1 per target resource type - to be decided upon), which means that for this repo only 3 to 6 would be included.

While I'm sure the YML-pipelines you have available are very usefull, to me it currently feels that the right location for these would be the '[arcus-azure/azure-devops-templates](https://github.com/arcus-azure/azure-devops-templates)'-repo.

Regarding the PS-script you've got, these seem like a good addition as we don't have anything related to cognitive services yet.

As you've noticed, this repo is still a work in progress and the initial setup for v0.1 still needs to be done, which is why I would like to schedule this to be included in v0.2 instead. 

What you could do, in the meantime, is add a separate branch and include those scripts underneath it. This way we don't lose track of them and/or they might already get reviewed.
Later on we'll either merge them into the master-branch and have them included in v0.1, or we'll copy them into a new branch based on the correct structure.

**Comment by paul-warwick-cdt** [comment]
Understood. Will do.

**Comment by pim-simons** [comment]
@paul-warwick-cdt we are looking through the open issues in GitHub.
This issue is quite old, is this still relevant?
